env:
  browser: true #基本はこれでよい
  es2021: true
extends:
  - eslint:recommended # eslintの推奨ルール
  # - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - "@nuxt/eslint-config"
  - prettier # prettierを併用する場合必要

parser: 'vue-eslint-parser' # vue/typescript併用の場合はこのperserを指定
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser' # typescript用perser
  project: true
  extraFileExtensions:
    - '.vue'
plugins:
  - vue
rules: {}
