on:
  push:
    branches:
      - production

name: Build and Deploy to Cloud Run
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: ${{secrets.SERVICE_NAME}}
  MICROCMS_SERVEICE_ID: ${{ secrets.MICROCMS_SERVEICE_ID }}
  MICROCMS_API: ${{ secrets.MICROCMS_API }}
  HOST: 0.0.0.0
  PORT: 8080
  BASE_URL: https://poripority.com
  GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{secrets.SERVICE_ACCOUNT_NAME }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |-
           docker build -t asia.gcr.io/${{ secrets.PROJECT_ID}}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
            --build-arg _NODE_ENV=pruduction \
            --build-arg _MICROCMS_API=${{ secrets.MICROCMS_API}} \
            --build-arg _MICROCMS_SERVEICE_ID=${{ secrets.MICROCMS_SERVEICE_ID}} \
            --build-arg _BASE_URL=$BASE_URL \
            --build-arg _GA_MEASUREMENT_ID=${{ secrets.GA_MEASUREMENT_ID}} \
            ./ \

      - name: Push Docker Image
        run: docker push asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --project=$PROJECT_ID \
            --image=asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
            --region="asia-northeast2" \
            --service-account=${{secrets.SERVICE_ACCOUNT_NAME }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --cpu-boost \
            --max-instances 3


